n_poses: 88     # 88 -> 20*60
n_codes: 30
motion_resampling_framerate: 20     # 20 -> 60
subdivision_stride: 10      # 10 -> 200
batch_size: 8       # 384 -> 32
loader_workers: 12
epochs: 512     # 500 -> 10
save_per_epochs: 25     # 20 -> 1
log_interval: 50
weight_decay: 0.0
lr_anneal_steps: 0
# upper-body-only
upper: False

audio_feat: "wavlm"     # wav encoder; mfcc; wavlm

mode: 'audio_pharse'      #(audio_only, audio_pharse, audio_text)
# audio_pharse mode
pharse: ['Kick,Forwards Walking'] 
# audio_text mode
locomotion_text: ['a person walks back and forth','a person sits down for a long time',''] 

# Noise Emotion Classifier
use_emo_classifier: 0
emotion: 'netural'             #(netural, happiness, anger, sadness, contempt, surprise, fear, disgust)


speaker_id: [1,0,0,0] # Speaker1: Wayne (boy)   Speaker2: Sophie (girl) Speaker3: Miranda (girl)  Speaker4: Kieks (boy)

lr: 0.00003     # 0.00003 ->
betas: [0.5, 0.999]
milestones: [100, 200]
gamma: 0.1

